### ISSUE TITLE
Fails to build with Tcl/Tk 9.0

### ISSUE THREAD

**Issue by berolinux** [CGNS/CGNS#830]
CGNS fails to build with Tcl/Tk 9.0:

```
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:23:24: error: expected ';' after top level declarator
   23 | extern int CGIOtcl_Init _ANSI_ARGS_((Tcl_Interp *interp));
      |                        ^
      |                        ;
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:57:32: error: expected ';' at end of declaration
   57 |     extern int TK_LOCAL_APPINIT _ANSI_ARGS_((Tcl_Interp *interp));
      |                                ^
      |                                ;
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:70:25: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'Tcl_AppInitProc *' (aka 'int (*)(struct Tcl_Interp *)') [-Wint-conversion]
   70 |     Tk_Main(argc, argv, TK_LOCAL_APPINIT);
      |                         ^~~~~~~~~~~~~~~~
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:55:26: note: expanded from macro 'TK_LOCAL_APPINIT'
   55 | #define TK_LOCAL_APPINIT Tcl_AppInit
      |                          ^~~~~~~~~~~
/usr/include/tk.h:1517:57: note: expanded from macro 'Tk_Main'
 1517 | #define Tk_Main(argc, argv, proc) Tk_MainEx(argc, argv, proc, \
      |                                                         ^~~~
/usr/include/tkDecls.h:1815:19: note: passing argument to parameter 'appInitProc' here
 1815 |         Tcl_AppInitProc *appInitProc, Tcl_Interp *interp);
      |                          ^
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:43:1: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C23 [-Wdeprecated-non-prototype]
   43 | main(argc, argv)
      | ^
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:94:1: error: redefinition of 'Tcl_AppInit' as different kind of symbol
   94 | Tcl_AppInit(interp)
      | ^
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:57:16: note: previous definition is here
   57 |     extern int TK_LOCAL_APPINIT _ANSI_ARGS_((Tcl_Interp *interp));
      |                ^
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:55:26: note: expanded from macro 'TK_LOCAL_APPINIT'
   55 | #define TK_LOCAL_APPINIT Tcl_AppInit
      |                          ^
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:129:21: error: called object type 'int' is not a function or function pointer
  129 |     if (CGIOtcl_Init(interp) == TCL_ERROR)
      |         ~~~~~~~~~~~~^
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:94:1: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C23 [-Wdeprecated-non-prototype]
   94 | Tcl_AppInit(interp)
      | ^
2 warnings and 5 errors generated.
```

**Comment by brtnfld** [comment]
@MicK7, do you think this can be closed?

**Comment by MicK7** [comment]
No it can't be closed. The build will fail with a different error.
There is a `#ifdef Tcl_Size`  that need to be changed to support tcl/tk 9.  The question is  how do we switch to the 9 version ? Do we drop 8.6 ?

**Comment by brtnfld** [comment]
I have a PR, but I need to install 9.0 to test.
