### PR TITLE
Fix Tcl/Tk 9.0 compatibility by properly handling Tcl_Size type

### LINKED ISSUE #830: Fails to build with Tcl/Tk 9.0
CGNS fails to build with Tcl/Tk 9.0:

```
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:23:24: error: expected ';' after top level declarator
   23 | extern int CGIOtcl_Init _ANSI_ARGS_((Tcl_Interp *interp));
      |                        ^
      |                        ;
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:57:32: error: expected ';' at end of declaration
   57 |     extern int TK_LOCAL_APPINIT _ANSI_ARGS_((Tcl_Interp *interp));
      |                                ^
      |                                ;
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:70:25: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'Tcl_AppInitProc *' (aka 'int (*)(struct Tcl_Interp *)') [-Wint-conversion]
   70 |     Tk_Main(argc, argv, TK_LOCAL_APPINIT);
      |                         ^~~~~~~~~~~~~~~~
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:55:26: note: expanded from macro 'TK_LOCAL_APPINIT'
   55 | #define TK_LOCAL_APPINIT Tcl_AppInit
      |                          ^~~~~~~~~~~
/usr/include/tk.h:1517:57: note: expanded from macro 'Tk_Main'
 1517 | #define Tk_Main(argc, argv, proc) Tk_MainEx(argc, argv, proc, \
      |                                                         ^~~~
/usr/include/tkDecls.h:1815:19: note: passing argument to parameter 'appInitProc' here
 1815 |         Tcl_AppInitProc *appInitProc, Tcl_Interp *interp);
      |                          ^
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:43:1: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C23 [-Wdeprecated-non-prototype]
   43 | main(argc, argv)
      | ^
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:94:1: error: redefinition of 'Tcl_AppInit' as different kind of symbol
   94 | Tcl_AppInit(interp)
      | ^
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:57:16: note: previous definition is here
   57 |     extern int TK_LOCAL_APPINIT _ANSI_ARGS_((Tcl_Interp *interp));
      |                ^
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:55:26: note: expanded from macro 'TK_LOCAL_APPINIT'
   55 | #define TK_LOCAL_APPINIT Tcl_AppInit
      |                          ^
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:129:21: error: called object type 'int' is not a function or function pointer
  129 |     if (CGIOtcl_Init(interp) == TCL_ERROR)
      |         ~~~~~~~~~~~~^
/home/bero/abf/cgns/BUILD/cgns-4.5.0-build/CGNS-4.5.0/src/cgnstools/cgnsview/cgiowish.c:94:1: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C23 [-Wdeprecated-non-prototype]
   94 | Tcl_AppInit(interp)
      | ^
2 warnings and 5 errors generated.
```

### PR DESCRIPTION
**Pull request by brtnfld**
Tcl/Tk 9.0 introduced Tcl_Size as a platform-appropriate type for sizes and counts (replacing int in many APIs). This fix ensures compatibility with both Tcl/Tk 8.6 and 9.0 by properly using Tcl_Size where required by the Tcl API while maintaining existing fallback support.

Fixes #830 

----

> [!IMPORTANT]
> Ensure Tcl/Tk 9.0 compatibility by using `Tcl_Size` for size/count variables in `cgnstcl.c` and `cgiotcl.c`, maintaining support for Tcl/Tk 8.6.
> 
>   - **Compatibility**:
>     - Use `Tcl_Size` instead of `int` for size/count variables in `cgnstcl.c` and `cgiotcl.c` to support Tcl/Tk 9.0.
>     - Maintain compatibility with Tcl/Tk 8.6 by using conditional compilation.
>   - **Code Changes**:
>     - Replace `int` with `Tcl_Size` for variables like `ndim` and `np` in functions such as `CGIOdimensions` and `CGIOwrite` in `cgiotcl.c`.
>     - Adjust loops and type casts to accommodate `Tcl_Size` in `cgnstcl.c` and `cgiotcl.c`.
>   - **Misc**:
>     - Fixes #830.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=CGNS%2FCGNS&utm_source=github&utm_medium=referral)<sup> for 27c83ab665370fcce42e59beb1e1c754acc1e3c1. You can [customize](https://app.ellipsis.dev/CGNS/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by brtnfld** [comment]
I've checked both 8.6 and 9.0 works

**Review by MicK7 — APPROVED** [review]

**Comment by opoplawski** [comment]
It appears that this is not present in 4.5.2.  When will this make it into a released version?
