### ISSUE TITLE
[SOURCEFORGE-12] pcgns_util.c fails to compile

### ISSUE THREAD

**Issue by brtnfld** [CGNS/CGNS#389]
cgnslib\_3.1.3 fails to compile in Ubuntu 11.10 with parallel support.

Compiler gives following error message:

/home/user/cgnslib\_3.1.3/pcgns/src/pcgns\_util.c: Function ”new\_str\_attb”:
/home/user/cgnslib\_3.1.3/pcgns/src/pcgns\_util.c:264:2: error: too many arguments to function ”H5Acreate1”
/usr/include/H5Apublic.h:105:16: note: declared here

and two similar errors follow.

With Ubuntu 11.10 HDF5 library is compiled with option --with-default-api-version=v16 as there are these two lines in libhdf5.settings:

...
Default API Mapping: v16
With Deprecated Public Symbols: yes
...

It seems that pcgns\_util.c uses old functions by default even if it should use newer ones. With hard-coded to use function H5Acreate2 compiling finishes without errors.

Expected behaviour: Compiling finishes without errors.
Current behaviour: Wrong version from function seems to be selected for pcgns\_util.c and build process fails.

Reported by: grinda

**Comment by brtnfld** [comment]
Closing this SourceForge migration from 2012. `pcgns_util.c` no longer exists in the repository — the parallel utilities were restructured. No longer applicable.
