### ISSUE TITLE
Call to undeclared internal Tk function TkWmAddToColormapWindows in tkogl

### ISSUE THREAD

**Issue by fweimer-rh** [CGNS/CGNS#689]
In `src/cgnstools/tkogl/tkogl.c`, there is a call to `TkWmAddToColormapWindows`, but this function is only declared in the private/unsupported Tk headers. This will fail to build with future compilers which do not support implicit function declarations.

**Comment by awoimbee** [comment]
I understand we need to `#include <tk-private/generic/tkInt.h>` (unless a TK dark mage wants to help remove the call to `TkWmAddToColormapWindows`), but `#define _TKPORT` is a very dirty hack that I don't understand.
On my machine(™) I have both `tkPort.h` and `tkUnixPort.h`.

**Comment by brtnfld** [comment]
For OpenSuse, tk-private/generic does not exist, tkInt.h is installed in /usr/include

**Comment by drew-parsons** [comment]
> +/* For TkWmAddToColormapWindows. */
> +#define _TKPORT /* Typical installations cannot find tkPort.h. */
> +#include <tk-private/generic/tkInt.h>
> +

For what it's worth, this workaround does not work with tcl 8.6 (debian installation), at least not with the cgns 4.2.0 source which debian has in experimental build,
```
[ 69%] Building C object src/cgnstools/tkogl/CMakeFiles/tkogl.dir/tkogl.c.o
cd /projects/misc/build/libcgns/obj-x86_64-linux-gnu/src/cgnstools/tkogl && /usr/bin/cc -DH5_BUILT_AS_STATIC_LIB -I/projects/misc/build/libcgns/obj-x86_64-linux-gnu/src -I/projects/misc/build/libcgns/src -I/usr/include/hdf5/serial -I/usr/include/tcl -I/projects/misc/build/libcgns/src/cgnstools/tkogl/../common -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/projects/misc/build/libcgns=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu99 -std=gnu99 -MD -MT src/cgnstools/tkogl/CMakeFiles/tkogl.dir/tkogl.c.o -MF CMakeFiles/tkogl.dir/tkogl.c.o.d -o CMakeFiles/tkogl.dir/tkogl.c.o -c /projects/misc/build/libcgns/src/cgnstools/tkogl/tkogl.c
/projects/misc/build/libcgns/src/cgnstools/tkogl/tkogl.c: In function ‘OGLwinCmd’:
/projects/misc/build/libcgns/src/cgnstools/tkogl/tkogl.c:606:33: error: passing argument 1 of ‘TkWmAddToColormapWindows’ from incompatible pointer type [-Wincompatible-pointer-types]
  606 |        TkWmAddToColormapWindows(tkwin);
      |                                 ^~~~~
      |                                 |
      |                                 Tk_Window {aka struct Tk_Window_ *}
In file included from /usr/include/tcl/tk-private/generic/tkInt.h:1090,
                 from /projects/misc/build/libcgns/src/cgnstools/tkogl/tkogl.c:27:
/usr/include/tcl/tk-private/generic/tkIntDecls.h:278:60: note: expected ‘TkWindow *’ but argument is of type ‘Tk_Window’ {aka ‘struct Tk_Window_ *’}
  278 | EXTERN void             TkWmAddToColormapWindows(TkWindow *winPtr);
      |                                                  ~~~~~~~~~~^~~~~~
In file included from /projects/misc/build/libcgns/src/cgnstools/tkogl/tkogl.h:9,
                 from /projects/misc/build/libcgns/src/cgnstools/tkogl/tkogl.c:14:
/usr/include/tcl/tk.h:139:28: note: ‘Tk_Window’ declared here
  139 | typedef struct Tk_Window_ *Tk_Window;
      |                            ^~~~~~~~~
make[3]: *** [src/cgnstools/tkogl/CMakeFiles/tkogl.dir/build.make:82: src/cgnstools/tkogl/CMakeFiles/tkogl.dir/tkogl.c.o] Error 1
```

**Comment by MicK7** [comment]
> > +/* For TkWmAddToColormapWindows. _/
> > +#define _TKPORT /_ Typical installations cannot find tkPort.h. */
> > +#include <tk-private/generic/tkInt.h>
> > +
> 
> For what it's worth, this workaround does not work with tcl 8.6 (debian installation), at least not with the cgns 4.2.0 source which debian has in experimental build,
> 
> ```
> [ 69%] Building C object src/cgnstools/tkogl/CMakeFiles/tkogl.dir/tkogl.c.o
> cd /projects/misc/build/libcgns/obj-x86_64-linux-gnu/src/cgnstools/tkogl && /usr/bin/cc -DH5_BUILT_AS_STATIC_LIB -I/projects/misc/build/libcgns/obj-x86_64-linux-gnu/src -I/projects/misc/build/libcgns/src -I/usr/include/hdf5/serial -I/usr/include/tcl -I/projects/misc/build/libcgns/src/cgnstools/tkogl/../common -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/projects/misc/build/libcgns=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu99 -std=gnu99 -MD -MT src/cgnstools/tkogl/CMakeFiles/tkogl.dir/tkogl.c.o -MF CMakeFiles/tkogl.dir/tkogl.c.o.d -o CMakeFiles/tkogl.dir/tkogl.c.o -c /projects/misc/build/libcgns/src/cgnstools/tkogl/tkogl.c
> /projects/misc/build/libcgns/src/cgnstools/tkogl/tkogl.c: In function ‘OGLwinCmd’:
> /projects/misc/build/libcgns/src/cgnstools/tkogl/tkogl.c:606:33: error: passing argument 1 of ‘TkWmAddToColormapWindows’ from incompatible pointer type [-Wincompatible-pointer-types]
>   606 |        TkWmAddToColormapWindows(tkwin);
>       |                                 ^~~~~
>       |                                 |
>       |                                 Tk_Window {aka struct Tk_Window_ *}
> In file included from /usr/include/tcl/tk-private/generic/tkInt.h:1090,
>                  from /projects/misc/build/libcgns/src/cgnstools/tkogl/tkogl.c:27:
> /usr/include/tcl/tk-private/generic/tkIntDecls.h:278:60: note: expected ‘TkWindow *’ but argument is of type ‘Tk_Window’ {aka ‘struct Tk_Window_ *’}
>   278 | EXTERN void             TkWmAddToColormapWindows(TkWindow *winPtr);
>       |                                                  ~~~~~~~~~~^~~~~~
> In file included from /projects/misc/build/libcgns/src/cgnstools/tkogl/tkogl.h:9,
>                  from /projects/misc/build/libcgns/src/cgnstools/tkogl/tkogl.c:14:
> /usr/include/tcl/tk.h:139:28: note: ‘Tk_Window’ declared here
>   139 | typedef struct Tk_Window_ *Tk_Window;
>       |                            ^~~~~~~~~
> make[3]: *** [src/cgnstools/tkogl/CMakeFiles/tkogl.dir/build.make:82: src/cgnstools/tkogl/CMakeFiles/tkogl.dir/tkogl.c.o] Error 1
> ```

This may be a different issue as I have no problem building and installing cgns 4.5.0 from source on debian Trixie...

**Comment by brtnfld** [comment]
I have the same issue with develop and OpenSUSE Tumbleweed, see PR #868 for a fix. This passes on OpenSUSE.

**Comment by drew-parsons** [comment]
Too many patches for this issue. I'd tried #757 but it failed too (I hadn't tried #868). Sounds like it got fixed by version 4.5.0. Best for Debian to just update its source version instead of hacking patches.
