### ISSUE TITLE
[CGNS-196] cgnstools fail to build in 4.1.0 release: undefined reference to `cgio_read_all_data'

### ISSUE THREAD

**Issue by brtnfld** [CGNS/CGNS#591]
> This issue has been imported from JIRA. Read the [original ticket here](https://cgnsorg.atlassian.net/browse/CGNS-196).

- _**Created at:**_ Wed, 4 Mar 2020 18:23:01 -0600
- _**Resolved at:**_ Sat, 14 Mar 2020 11:28:47 -0500

<p>Probably due to modifications to cgio API.  Building the library itself works fine but with '-DCGNS_BUILD_CGNSTOOLS:BOOL=ON', it fails.</p>

**Comment by brtnfld** [comment]
> This comment has been imported from JIRA. Read the [original comment here](https://cgnsorg.atlassian.net/browse/CGNS-196#comment-13902).

- _**Created at:**_ Wed, 4 Mar 2020 22:28:36 -0600

<p>./utilities/update_ngon.c:    if (cgio_read_all_data(cgio_num, elem_id, data) &#33;= CG_OK) {<br/>
./utilities/update_ngon.c:    cgio_read_all_data(cgio_num, connect_id, (void *)connectivity);<br/>
./utilities/update_ngon.c:    cgio_read_all_data(cgio_num, connect_id, (void *)connectivity);<br/>
./utilities/update_ngon.c:    cgio_read_all_data(cgio_num, connect_id, (void *)connectivity);<br/>
./utilities/update_ngon.c:    cgio_read_all_data(cgio_num, connect_id, (void <em>)connectivity);</em><br/>
<em>./utilities/update_ngon.c:    if (cgio_read_all_data(cgio_num, childid, (void</em>)data) &#33;= CG_OK) {<br/>
./utilities/update_ngon.c:0 == cgio_read_all_data (inpcg, node_id, &cgns_version)) {<br/>
./cgnsview/cgiotcl.c:if (cgio_read_all_data (cgioNum, node_id, olddata)) {<br/>
./cgnsview/cgiotcl.c:    return (get_error (interp, "cgio_read_all_data"));<br/>
./cgnsview/cgiotcl.c:    if (cgio_read_all_data (cgioNum, node_id, values)) {<br/>
./cgnsview/cgiotcl.c:return (get_error (interp, "cgio_read_all_data"));<br/>
./calclib/calc.c:    if (cgio_read_all_data (cgio, nodeid, values)) {</p>

**Comment by brtnfld** [comment]
> This comment has been imported from JIRA. Read the [original comment here](https://cgnsorg.atlassian.net/browse/CGNS-196#comment-13907).

- _**Created at:**_ Sat, 14 Mar 2020 11:28:47 -0500

<p>Removed missing APIs</p>
