### ISSUE TITLE
Compilation in depending projects: error: redefinition of 'Pair'

### ISSUE THREAD

**Issue by yurivict** [CGNS/CGNS#863]
The gmsh python module fails to compile with cgnslib-4.5.0:
```
In file included from /usr/ports/cad/py-gmsh/work-py311/gmsh-4.13.1-source/src/geo/GModelIO_CGNS.cpp:9:
In file included from /usr/ports/cad/py-gmsh/work-py311/gmsh-4.13.1-source/src/geo/CGNSCommon.h:16:
/usr/local/include/cgnslib.h:632:15: error: redefinition of 'Pair'
  632 |   CGNS_ENUMV( Pair ) =7,
      |               ^
/usr/ports/cad/py-gmsh/work-py311/gmsh-4.13.1-source/src/geo/Pair.h:10:35: note: previous definition is here
   10 | template <class L, class R> class Pair {
      |                                   ^
1 error generated.
```

Could you please rename offending symbols?

Version: 4.5.0
clang-19
FreeBSD 14.3

Thanks,
Yuri
