### PR TITLE
Cgns196

### PR DESCRIPTION
**Pull request by brtnfld**
Fixed: CGNS-196
cgnstools fail to build in 4.1.0 release: undefined reference to `cgio_read_all_data'

### CODE REVIEW

File: .travis.yml [hunk 1]
```diff
@@ -20,6 +20,7 @@ before_install:
          sudo apt-get install -qq gfortran;
          sudo apt-get install -qq libmpich-dev;
          sudo apt-get install -qq mpich;
+         sudo apt-get install -qq libgl1-mesa-glx libglu1-mesa-dev libxmu-dev tk-dev tcl-dev;
```
Comment (MicK7) [inline .travis.yml]:
```suggestion
         sudo apt-get install -qq libgl1-mesa-glx libglu1-mesa-dev libxmu-dev tk tcl tk-dev tcl-dev;
```

File: bin/config-cgns.sh [hunk 2]
```diff
@@ -8,7 +8,9 @@ OPTS=""
 if [ $TRAVIS_OS_NAME = "linux" ]; then
   export FLIBS="-Wl,--no-as-needed -ldl"
   export LIBS="-Wl,--no-as-needed -ldl"
-  OPTS="--enable-parallel"
+  OPTS="--enable-parallel --enable-cgnstools --with-tcl=/usr/lib64 --with-tk=/usr/lib64"
```
Comment (MicK7) [inline bin/config-cgns.sh]:
```suggestion
  OPTS="--enable-parallel --enable-cgnstools --with-tcl=/usr/lib/x86_64-linux-gnu --with-tk=/usr/lib/x86_64-linux-gnu"
```

File: .travis.yml [hunk 3]
```diff
@@ -20,6 +20,7 @@ before_install:
          sudo apt-get install -qq gfortran;
          sudo apt-get install -qq libmpich-dev;
          sudo apt-get install -qq mpich;
+         sudo apt-get install -qq libgl1-mesa-glx libglu1-mesa-dev libxmu-dev tk tcl tk-dev tcl-dev;
```
Comment (MicK7) [inline .travis.yml]:
```suggestion
         sudo apt-get install -qq libgl1-mesa-glx libglu1-mesa-dev libxmu-dev tk-dev tcl-dev;
```
